# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-7.13

# User packages to be built.
packages:
- '.'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- fbmessenger-api-0.1.2.1
- telegram-api-0.5.0.1
- persistent-mysql-2.6
- aeson-1.0.2.1
- mysql-0.1.4
- mysql-simple-0.4.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

pvp-bounds: both
